version: "3.1"
services:

    manage-app:
#        image: kwsilence/manage-app:render
        build: .
        container_name: java_spring_app
        depends_on:
            - manage-db
        ports:
            - "8080:8080"
        networks:
            - manage-network
        environment:
            - MANAGE_ROOT_USER=admin
            - MANAGE_ROOT_PASS=admin
            - DB_HOST=manage-db
            - DB_PORT=5432
            - DB_USER=manageadmin
            - DB_PASSWORD=kws
        restart: always

    manage-db:
        image: postgres
        container_name: java_spring_db
        ports:
            - "5432:5432"
        networks:
            - manage-network
        environment:
            - POSTGRES_DB=manage
            - POSTGRES_USER=manageadmin
            - POSTGRES_PASSWORD=kws
        restart: always

networks:
    manage-network:
