name: Publish docker image and deploy to Render

on:
  push:
    branches:
      - 'render'

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push for Windows
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-windows
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:render

#  render-deploy:
#    needs: [ docker-image ]
#    runs-on: ubuntu-latest
